---
global:
  pattern: layered-zero-trust
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: coco-dev
  gitOpsRepo: https://github.com/beraldoleal/layered-zero-trust
  gitOpsBranch: lzt-osc-113-upgrade
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
